### ISSUE TITLE
xml2js-es6-promise compatible with angular2 aot

### ISSUE THREAD

**Issue by Pilukina** [leonatherton/xml2js-es6-promise#2]
Good morning, 
I find very useful your library, many thanks for it!

But I have problem to compile it using the angular 2 ngc compilar (ahead of time compiler).
It could be a good idea to  publish your library including the  typings information (index.d.ts file or maybe the @type/xml2js-es6-promise) in order to make it compatible with Angular 2 applications.

If you decide to make it, please, let me know and I'll wait for your new release, otherwise I'll try to find another solution for my problem.
Again, many thanks.

Kind Regards,

Pilar

**Comment by leonatherton** [comment]
Thanks for raising this. I have not used Angular before so will need to read up and learn how to add compatibility.

As a workaround I would suggest implementing your own es6 wrapper for xml2js in your project. It is only about [10 lines of code](https://github.com/leonatherton/xml2js-es6-promise/blob/master/xml2js-es6-promise.js).
